### ISSUE TITLE
Add ability to edit time or add time entry manually 

### ISSUE THREAD

**Issue by Gotterbild** [lakoliu/Furtherance#44] opened 2022-05-17 08:42 UTC
The app definitely lacks ability to add time manually. 

Sometimes I forget to enable timer and when I find that out, I could add time manually. However, right now app doesn't allow to do that.

Also, it will be great to have ability edit a record manually. I suppose it will be the same UI as adding a record.

**Comment by lakoliu** [comment] 2022-05-18 06:32
Furtherance already supports editing a task. You can change the name, tags, start, and stop times. Right now, that is the best way to add a task manually - start a task with the name you want, then stop it and immediately go in and edit it to the correct time.

Adding tasks manually is on my list of things to add. I'm going to close this as a duplicate of Issue #42.

**Closed by lakoliu** 2022-05-18 06:32 UTC
Labels: feature request

**Comment by Gotterbild** [comment] 2022-05-18 06:38
@lakoliu 
OK, sounds great!

But how to do it? There's no explanation anywhere. UI doesn't give a hint.

**Comment by lakoliu** [comment] 2022-05-18 06:42
Yeah, that's true. I hope to add documentation of some type to the app in the future. Once a task is in the list, click on it. Then click the time under either Start or Stop and it will bring up the dialog to edit everything.

**Comment by Gotterbild** [comment] 2022-05-18 07:03
@lakoliu 
I'm a frontend developer and UX designer myself. And I can say that if feature requires documentation, that means the UI is bad.

It will be much better to just use the pattern everybody is used to - a button.

Same applies to right button click on record to start tracking. It will be much better to make a button (additionally or instead).
