### ISSUE TITLE
Weekly time summary

### ISSUE THREAD

**Issue by toger5** [lakoliu/Furtherance#46] opened 2022-05-23 09:20 UTC
It would be great if I could get a more detailed report. At least summing up weekly hours would be really nice. Maybe even monthly. It would also be really nice to have something like a summary page that gives me some statistics.
Thanks a lot for the app I actively use it and find it really beautiful.

**Comment by toger5** [comment] 2022-05-23 09:21
This would also be solved with the solution of https://github.com/lakoliu/Furtherance/issues/32
So maybe this can be considered as a duplicate. Feel free to close it if they are too similar.

**Comment by lakoliu** [comment] 2022-05-25 05:14
Thanks for your suggestions. This is going to be the next major feature of Furtherance and I've already started doing some work on it. Hopefully it won't be too long before it's ready. I will close this as a duplicate of Issue #32. I'm happy Furtherance has been useful for you! Thanks again.

**Closed by lakoliu** 2022-05-25 05:14 UTC
