### ISSUE TITLE
Update Coloration to Match Libadwaita 1.4/GNOME 45

### ISSUE THREAD

**Issue by LSeelig** [lakoliu/Furtherance#128] opened 2024-02-08 19:38 UTC
GNOME 45 introduced an [update to Libadwaita](https://blogs.gnome.org/alicem/2023/09/15/libadwaita-1-4/) that, notably, changed headerbar color from grey to white in light mode. Furtherance should be updated for consistency with other GNOME apps.

**Comment by lakoliu** [comment] 2024-02-09 10:04
Cool, thank you for letting me know! I will get on updating Furtherance to the latest GTK/Libadwaita very soon.

**Comment by lakoliu** [comment] 2024-02-10 14:18
I just updated GTK and Libadwaita to the latest versions (444fd78), but in my tests the header bar was already the new white for Furtherance and the update did not cause a change. It could just be my system, but either way this update will be in the next release.

**Closed by lakoliu** 2024-02-10 14:18 UTC
Labels: enhancement

**Comment by gabrbrand** [comment] 2024-02-10 22:33
You probably need to update "features" to "v1_4" (GNOME 45).

**Comment by lakoliu** [comment] 2024-02-11 09:17
I tried that and there was no difference. Even before I upgraded to the latest GTK and libadwaita, Furtherance has the new white header bar, unless I'm missing something. Here is a screenshot. Are you seeing something different?

![Furtherance-white-headerbar](https://github.com/lakoliu/Furtherance/assets/99976966/7200f296-2036-4769-96a4-67c8853e9b33)

**Comment by gabrbrand** [comment] 2024-02-11 10:51
I tried, but no difference on my side as well.

GNOME Software (v45.3) looks the same, so this works as intended.
![image](https://github.com/lakoliu/Furtherance/assets/98428543/9860a5ed-1db0-4bca-967d-64e04dc855fe)

**Comment by gabrbrand** [comment] 2024-02-12 15:53
The older runtime-version (v44) on Flathub is causing the issue.
(The runtime-version in this repo was already updated to v45 -> Headerbar was already white)
See https://github.com/flathub/com.lakoliu.Furtherance/issues/9
New widgets: https://github.com/lakoliu/Furtherance/pull/129
