### ISSUE TITLE
Panel indicator

### ISSUE THREAD

**Issue by lallenfrancisl** [lakoliu/Furtherance#49] opened 2022-05-28 22:14 UTC
A panel indicator would be really great. It would give a nice heads up into how much time have be spent and also would go nicely when using pomodoro timer

**Comment by lakoliu** [comment] 2022-05-29 07:16
I believe this is a duplicate of Issue #19, but let me know if I'm wrong. You can check that thread for the reasons I haven't implemented this. I do think it is a good idea and I would like to have it, but since Furtherance is a GTK app I try to follow the style guidelines and best practices of GNOME which are against panel indicators. I've still got it on the list for potential features in the future, but it isn't on the immediate to-do list. Thank you for bringing it up though, it's on my mind.

**Closed by lakoliu** 2022-05-29 07:16 UTC
Labels: feature request
