### ISSUE TITLE
Slightly too wide for mobile

### ISSUE THREAD

**Issue by bertob** [lakoliu/Furtherance#85] opened 2022-08-26 20:57 UTC
The min width seems to be somewhere around 390px, which is a little bit too wide for mobile. It needs to be 360px or lower.

This goes for both the main window and the New Task dialog:

![image](https://user-images.githubusercontent.com/1908896/186989561-63e86c9b-cafc-44e0-a628-5c6e1a73912a.png)

**Comment by lakoliu** [comment] 2022-08-28 18:33
This sounds like it may be related to issue #52. If the problem is just the width I should be able to get that fixed without much issue. I will look into this as soon as I have some time in the coming days. Thanks for bringing this up!

**Comment by lakoliu** [comment] 2022-09-11 13:25
This should be fixed in the next release. As mentioned in #52, some of the windows may still be cut off, and I am working on a way to fix that, but the main page should work.

**Closed by lakoliu** 2022-09-11 13:25 UTC
Labels: bug
